insert into public.anime (id,title,mal_id,is_hero,in_catalog,dubbing_team,dubbed_characters,poster,cover_banner,story,sort_order) values
('Attack on Titan: No Regrets','Attack on Titan: No Regrets',25781,false,true,'black_echo','{}'::jsonb,NULL,NULL,NULL,1),
('jaadugar','Jaadugar',61483,false,true,'black_echo','{"Shira":"عبد الرزاق","Tolui":"عبد الرزاق","Uncle":"mohamed.arata","Sitara":"شيرو","Muhammad":"حاتم","Zumuld":"كنجي","Fatima":"makoto_san00"}'::jsonb,NULL,NULL,NULL,2),
('wind breaker','Wind Breaker',54900,true,true,'black_echo','{"Sakura, Haruka":"عبد الرزاق","Suou, Hayato":"mohamed akram","Tachibana, Kotoha":" Makoto_san","Hiiragi, Touma":"احمد منصور"}'::jsonb,NULL,NULL,NULL,3),
('Super Dragon Ball Heroes','Super Dragon Ball Heroes',37885,false,true,'دبلجة: فريق اكاتسكي','{"Son, Gokuu":"غوكو سون (مدبلج)"}'::jsonb,NULL,NULL,NULL,4),
('Blue Lock','Blue Lock',49596,false,true,'دبلجة: فريق crunchyroll','{"Isagi, Yoichi":"يويتشي إيساغي (مدبلج)","Bachira, Meguru":"ميغورو باتشيرا (مدبلج)"}'::jsonb,NULL,NULL,NULL,5),
('One Punch Man','One Punch Man',31772,false,true,'noor shadow','{}'::jsonb,NULL,NULL,NULL,6),
('Blue Lock2','Blue Lock 2',54865,false,true,'دبلجة: فريق crunchyroll','{}'::jsonb,NULL,NULL,NULL,7),
('Jujutsu Kaisen','Jujutsu Kaisen',40748,false,true,'دبلجة: فريق crunchyroll','{}'::jsonb,NULL,NULL,NULL,8),
('Jujutsu-Kaisen-2','Jujutsu Kaisen 2',51009,false,true,'دبلجة: فريق crunchyroll','{}'::jsonb,NULL,NULL,NULL,9),
('Jujutsu-Kaisen-3','Jujutsu Kaisen 3',57658,false,true,'دبلجة: فريق crunchyroll','{}'::jsonb,NULL,NULL,NULL,10),
('nijusseiki_denki_mokuroku:_eureka_evrika_مدبلج_s1','NIJUSSEIKI DENKI MOKUROKU: EUREKA EVRIKA مدبلج - الموسم 1',62856,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,11),
('yu☆gi☆oh!_sevens_مدبلج_s1','YU☆GI☆OH! SEVENS مدبلج - الموسم 1',40145,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,12),
('black_clover_مدبلج_s1','BLACK CLOVER مدبلج - الموسم 1',34572,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,13),
('charlotte_مدبلج_s1','CHARLOTTE مدبلج - الموسم 1',28999,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,14),
('grendizer_u_جريندايزر_يو_مدبلج_s1','GRENDIZER U جريندايزر يو مدبلج - الموسم 1',56189,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,15),
('gankutsuou_مدبلج_s1','GANKUTSUOU مدبلج - الموسم 1',239,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,16),
('hidarikiki_no_eren_مدبلج_s1','HIDARIKIKI NO EREN مدبلج - الموسم 1',53732,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,17),
('kuroko_no_basket_مدبلج_s1','KUROKO NO BASKET مدبلج - الموسم 1',11771,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,18),
('jigokuraku_مدبلج_s1','JIGOKURAKU مدبلج - الموسم 1',46569,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,19),
('jigokuraku_مدبلج_s3','JIGOKURAKU مدبلج - الموسم 2',46569,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,20),
('hanazakari_no_kimitachi_e_مدبلج_s1','HANAZAKARI NO KIMITACHI E مدبلج - الموسم 1',58861,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,21),
('tongari_boushi_no_atelier_مدبلج_s1','TONGARI BOUSHI NO ATELIER مدبلج - الموسم 1',51553,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,22),
('seihantai_na_kimi_to_boku_مدبلج_s1','SEIHANTAI NA KIMI TO BOKU مدبلج - الموسم 1',60371,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,23),
('hunter_x_hunter_(2011)_مدبلج_s1','HUNTER X HUNTER (2011) مدبلج - الموسم 1',11061,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,24),
('saikyou_no_shokugyou_wa_yuusha_demo_kenja_demo_naku_kanteishi_(kari)_rashii_desu_yo?_مدبلج_s1','SAIKYOU NO SHOKUGYOU WA YUUSHA DEMO KENJA DEMO NAKU KANTEISHI (KARI) RASHII DESU YO? مدبلج - الموسم 1',62825,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,25),
('dragon_quest:_dai_no_daibouken_(2020)_مدبلج_s1','DRAGON QUEST: DAI NO DAIBOUKEN (2020) مدبلج - الموسم 1',40906,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,26),
('enen_no_shouboutai_مدبلج_s1','ENEN NO SHOUBOUTAI مدبلج - الموسم 1',38671,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,27),
('enen_no_shouboutai_مدبلج_s2','ENEN NO SHOUBOUTAI مدبلج - الموسم 2',40956,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,28),
('enen_no_shouboutai_مدبلج_s3','ENEN NO SHOUBOUTAI مدبلج - الموسم 3',51818,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,29),
('enen_no_shouboutai_مدبلج_s4','ENEN NO SHOUBOUTAI مدبلج - الموسم 4',38671,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,30),
('جميع_مواسم_dr._stone_مدبلجة_s1','جميع مواسم DR. STONE مدبلجة - الموسم 1',38691,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,31),
('جميع_مواسم_dr._stone_مدبلجة_s2','جميع مواسم DR. STONE مدبلجة - الموسم 2',38691,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,32),
('جميع_مواسم_dr._stone_مدبلجة_s3','جميع مواسم DR. STONE مدبلجة - الموسم 3',38691,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,33),
('جميع_مواسم_dr._stone_مدبلجة_s4','جميع مواسم DR. STONE مدبلجة - الموسم 4',38691,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,34),
('جميع_مواسم_dr._stone_مدبلجة_s5','جميع مواسم DR. STONE مدبلجة - الموسم 5',38691,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,35),
('جميع_مواسم_dr._stone_مدبلجة_s6','جميع مواسم DR. STONE مدبلجة - الموسم 6',38691,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,36),
('جميع_مواسم_dr._stone_مدبلجة_s7','جميع مواسم DR. STONE مدبلجة - الموسم 7',38691,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,37),
('tokyo_magnitude_8.0_زلزال_طوكيو_مدبلج_s1','TOKYO MAGNITUDE 8.0 زلزال طوكيو مدبلج - الموسم 1',6211,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,38),
('all_out!!_مدبلج_s1','ALL OUT!! مدبلج - الموسم 1',31588,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,39),
('thunder_3_مدبلج_s1','THUNDER 3 مدبلج - الموسم 1',63418,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,40),
('shunkashuutou_daikousha:_haru_no_mai_مدبلج_s1','SHUNKASHUUTOU DAIKOUSHA: HARU NO MAI مدبلج - الموسم 1',61443,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,41),
('haikyuu!!_مدبلج_كامل_s1','HAIKYUU!! مدبلج كامل - الموسم 1',20583,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,42),
('steel_ball_run:_jojo_no_kimyou_na_bouken_مدبلج_s1','STEEL BALL RUN: JOJO NO KIMYOU NA BOUKEN مدبلج - الموسم 1',61469,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,43),
('mob_psycho_100_مدبلج_s1','MOB PSYCHO 100 مدبلج - الموسم 1',32182,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,44),
('donten_ni_warau_مدبلج_s1','DONTEN NI WARAU مدبلج - الموسم 1',21743,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,45),
('shibou_yuugi_de_meshi_wo_kuu._مدبلج_s1','SHIBOU YUUGI DE MESHI WO KUU. مدبلج - الموسم 1',59711,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,46),
('koori_no_jouheki_مدبلج_s1','KOORI NO JOUHEKI مدبلج - الموسم 1',60852,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,47),
('sono_bisque_doll_wa_koi_wo_suru_مدبلج_s1','SONO BISQUE DOLL WA KOI WO SURU مدبلج - الموسم 1',48736,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,48),
('boku_no_hero_academia_أكاديمية_بطلي_مدبلج_s1','BOKU NO HERO ACADEMIA أكاديمية بطلي مدبلج - الموسم 1',31964,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,49),
('boku_no_hero_academia_أكاديمية_بطلي_مدبلج_s2','BOKU NO HERO ACADEMIA أكاديمية بطلي مدبلج - الموسم 2',33486,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,50),
('boku_no_hero_academia_أكاديمية_بطلي_مدبلج_s3','BOKU NO HERO ACADEMIA أكاديمية بطلي مدبلج - الموسم 3',36456,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,51),
('boku_no_hero_academia_أكاديمية_بطلي_مدبلج_s4','BOKU NO HERO ACADEMIA أكاديمية بطلي مدبلج - الموسم 4',38408,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,52),
('boku_no_hero_academia_أكاديمية_بطلي_مدبلج_s5','BOKU NO HERO ACADEMIA أكاديمية بطلي مدبلج - الموسم 5',41587,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,53),
('yuusha_party_wo_oidasareta_kiyoubinbou_مدبلج_s1','YUUSHA PARTY WO OIDASARETA KIYOUBINBOU مدبلج - الموسم 1',61128,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,54),
('the_marginal_service_الخدمة_الخفية_مدبلج_s1','THE MARGINAL SERVICE الخدمة الخفية مدبلج - الموسم 1',53587,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,55),
('sakamoto_days_مدبلج_s1','SAKAMOTO DAYS مدبلج - الموسم 1',58939,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,56),
('sakamoto_days_مدبلج_s2','SAKAMOTO DAYS مدبلج - الموسم 2',58939,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,57),
('ore_dake_level_up_na_ken_مدبلج_s1','ORE DAKE LEVEL UP NA KEN مدبلج - الموسم 1',52299,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,58),
('ore_dake_level_up_na_ken_مدبلج_s2','ORE DAKE LEVEL UP NA KEN مدبلج - الموسم 2',52299,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,59),
('tensei_shitara_slime_datta_ken_مدبلج_s1','TENSEI SHITARA SLIME DATTA KEN مدبلج - الموسم 1',37430,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,60),
('tensei_shitara_slime_datta_ken_مدبلج_s2','TENSEI SHITARA SLIME DATTA KEN مدبلج - الموسم 2',39551,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,61),
('tensei_shitara_slime_datta_ken_مدبلج_s3','TENSEI SHITARA SLIME DATTA KEN مدبلج - الموسم 3',41487,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,62),
('tensei_shitara_slime_datta_ken_مدبلج_s4','TENSEI SHITARA SLIME DATTA KEN مدبلج - الموسم 4',53580,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,63),
('tensei_shitara_slime_datta_ken_مدبلج_s5','TENSEI SHITARA SLIME DATTA KEN مدبلج - الموسم 5',59970,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,64),
('shiguang_dailiren_مدبلج_s1','SHIGUANG DAILIREN مدبلج - الموسم 1',44074,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,65),
('shiguang_dailiren_مدبلج_s2','SHIGUANG DAILIREN مدبلج - الموسم 2',44074,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,66),
('bleach:_sennen_kessen-hen_مدبلج_s1','BLEACH: SENNEN KESSEN-HEN مدبلج - الموسم 1',41467,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,67),
('dead_account_مدبلج_s1','DEAD ACCOUNT مدبلج - الموسم 1',61196,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,68),
('baki-dou_مدبلج_s1','BAKI-DOU مدبلج - الموسم 1',58573,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,69),
('baki-dou_مدبلج_s2','BAKI-DOU مدبلج - الموسم 2',63833,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,70),
('yuusha-kei_ni_shosu:_choubatsu_yuusha_9004-tai_keimu_kiroku_مدبلج_s1','YUUSHA-KEI NI SHOSU: CHOUBATSU YUUSHA 9004-TAI KEIMU KIROKU مدبلج - الموسم 1',56009,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,71),
('usagi_drop_قطر_الندى_مدبلج_s1','USAGI DROP قطر الندى مدبلج - الموسم 1',10162,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,72),
('megalo_box_مدبلج_s1','MEGALO BOX مدبلج - الموسم 1',36563,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,73),
('megalo_box_مدبلج_s2','MEGALO BOX مدبلج - الموسم 2',36563,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,74),
('himekishi_wa_barbaroi_no_yome_مدبلج_s1','HIMEKISHI WA BARBAROI NO YOME مدبلج - الموسم 1',60028,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,75),
('fumetsu_no_anata_e_مدبلج_s1','FUMETSU NO ANATA E مدبلج - الموسم 1',41025,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,76),
('black_torch_مدبلج_s1','BLACK TORCH مدبلج - الموسم 1',61169,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,77),
('level_1_dakedo_unique_skill_de_saikyou_desu_مدبلج_s1','LEVEL 1 DAKEDO UNIQUE SKILL DE SAIKYOU DESU مدبلج - الموسم 1',51764,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,78),
('clevatess_ii:_majuu_no_ou_to_itsuwari_no_yuusha_denshou_مدبلج_s1','CLEVATESS II: MAJUU NO OU TO ITSUWARI NO YUUSHA DENSHOU مدبلج - الموسم 1',62513,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,79),
('dandelion_مدبلج_s1','DANDELION مدبلج - الموسم 1',63572,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,80),
('yomi_no_tsugai_مدبلج_s1','YOMI NO TSUGAI مدبلج - الموسم 1',62001,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,81),
('magic_kaito_1412_مدبلج_s1','MAGIC KAITO 1412 مدبلج - الموسم 1',25517,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,82),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s1','RE:ZERO KARA HAJIMERU ISEKAI SEIKATSU: SHIN HENSHUU-BAN مدبلج - الموسم 1',31240,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,83),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s2','RE:ZERO KARA HAJIMERU ISEKAI SEIKATSU: SHIN HENSHUU-BAN مدبلج - الموسم 2',39587,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,84),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s3','RE:ZERO KARA HAJIMERU ISEKAI SEIKATSU: SHIN HENSHUU-BAN مدبلج - الموسم 3',42203,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,85),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s4','RE:ZERO KARA HAJIMERU ISEKAI SEIKATSU: SHIN HENSHUU-BAN مدبلج - الموسم 4',54857,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,86),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5','RE:ZERO KARA HAJIMERU ISEKAI SEIKATSU: SHIN HENSHUU-BAN مدبلج - الموسم 5',61316,false,true,NULL,'{}'::jsonb,NULL,NULL,NULL,87),
('Ore dake Level Up na Ken Solo Leveling',NULL,52299,false,false,'دبلجة: فريق crunchyroll','{}'::jsonb,NULL,NULL,NULL,0),
('nijusseiki_denki_mokuroku:_eureka_evrika_مدبلج_s2',NULL,62856,false,false,NULL,'{}'::jsonb,NULL,NULL,NULL,0),
('jujutsu_kaisen_مدبلج_s1',NULL,40748,false,false,NULL,'{}'::jsonb,NULL,NULL,NULL,0),
('jujutsu_kaisen_مدبلج_s2',NULL,51009,false,false,NULL,'{}'::jsonb,NULL,NULL,NULL,0),
('jujutsu_kaisen_مدبلج_s3',NULL,57658,false,false,NULL,'{}'::jsonb,NULL,NULL,NULL,0)
on conflict (id) do nothing;
