insert into public.episodes (anime_id,number,title,thumbnail,duration,release_date,dubbing_team,servers) values
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',1,'الحلقة 1','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/C991ZUZLZAHx8","ouo_url":"https://ouo.io/g0y15b"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/C991ZUZLZAHx8","ouo_url":"https://ouo.io/g0y15b"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',2,'الحلقة 2','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/vyYFGNYXMMDVp","ouo_url":"https://ouo.io/xl6VZA"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/vyYFGNYXMMDVp","ouo_url":"https://ouo.io/xl6VZA"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',3,'الحلقة 3','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/BFWLmBU68DvUK","ouo_url":"https://ouo.io/FdUSw5"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/BFWLmBU68DvUK","ouo_url":"https://ouo.io/FdUSw5"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',4,'الحلقة 4','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/9pF1zZ1sTd9se","ouo_url":"https://ouo.io/Nhvoadw"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/9pF1zZ1sTd9se","ouo_url":"https://ouo.io/Nhvoadw"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',5,'الحلقة 5','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/9xZI0aTvY4nIJ","ouo_url":"https://ouo.io/oleEme"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/9xZI0aTvY4nIJ","ouo_url":"https://ouo.io/oleEme"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',6,'الحلقة 6','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/IBczsFG0z1oWr","ouo_url":"https://ouo.io/eZCBVL"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/IBczsFG0z1oWr","ouo_url":"https://ouo.io/eZCBVL"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',7,'الحلقة 7','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/ubpu7sbDQvyrd","ouo_url":"https://ouo.io/rg24c8"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/ubpu7sbDQvyrd","ouo_url":"https://ouo.io/rg24c8"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',8,'الحلقة 8','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/iHr2UaxwVDhtu","ouo_url":"https://ouo.io/9t70G2"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/iHr2UaxwVDhtu","ouo_url":"https://ouo.io/9t70G2"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',9,'الحلقة 9','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/K86yMGw75lDYE","ouo_url":"https://ouo.io/ci7wXR"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/K86yMGw75lDYE","ouo_url":"https://ouo.io/ci7wXR"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',10,'الحلقة 10','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/xm10Y8gvawL79","ouo_url":"https://ouo.io/BLD3gc"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/xm10Y8gvawL79","ouo_url":"https://ouo.io/BLD3gc"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',11,'الحلقة 11','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/V5iuutoeZ0IbN","ouo_url":"https://ouo.io/7e6hHj1"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/V5iuutoeZ0IbN","ouo_url":"https://ouo.io/7e6hHj1"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',12,'الحلقة 12','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/DIP9LhK1zwpm9","ouo_url":"https://ouo.io/Tv003ve"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/DIP9LhK1zwpm9","ouo_url":"https://ouo.io/Tv003ve"}]'::jsonb),
('re:zero_kara_hajimeru_isekai_seikatsu:_shin_henshuu-ban_مدبلج_s5',13,'الحلقة 13','https://shahiid-anime.net/wp-content/uploads/Image-Apr-23-2026-01_20_05-AM-745x1024.png','24:00','Jun 28, 2026',NULL,'[{"name":"سيرفر رئيسي","url":"https://share4max.com/iframe/T6GZNiArMJRCg","ouo_url":"https://ouo.io/LZGwq3"},{"name":"سيرفر احتياطي 1","url":"https://share4max.com/iframe/T6GZNiArMJRCg","ouo_url":"https://ouo.io/LZGwq3"}]'::jsonb);
